# Solving a Matrix Equation Ax=b

## Using Solve

In [1]:

from numpy import *
from numpy.linalg import *
A=([[1,2,3],[22,32,42],[55,66,100]])
b=([1,2,3])
x=solve(A,b)
print('x = ',x)
y=dot(A,x)-b
print('y = ',y)

x =  [-1.4057971  -0.1884058   0.92753623]
y =  [0. 0. 0.]


## By finding inv of A

In [2]:
x=dot(inv(A),b)
print('x =',x)
y=dot(A,x)-b
print('y =',y)

x = [-1.4057971  -0.1884058   0.92753623]
y = [0. 0. 0.]


# Eigen Value Problem $$I\omega=\lambda \omega$$

In [5]:
I=array([[2/3,-1/4],[-1/4,2/3]])
Es,evectors=eig(I)
print('Eigen Value = '+str(Es))
print('')
print('Eigen vector matrix = \n'+str(evectors))
print('')
# Just Confirming below
Vec=array([evectors[0,0],evectors[1,0]])
print('Eigen Vectors ='+str(Vec)) #Only unique values
print('')
LHS=dot(I,Vec)
RHS=dot(Es[0],Vec)
Confirmation=LHS-RHS
print('Confirmation = '+str(Confirmation))

Eigen Value = [0.91666667 0.41666667]

Eigen vector matrix = 
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Eigen Vectors =[ 0.70710678 -0.70710678]

Confirmation = [ 1.11022302e-16 -1.11022302e-16]


# Exercise

In [7]:
from numpy import *
A=array([4,-2,1,3,6,-4,2,1,6])
print('A :'+str(A))
print('')
A=A.reshape((3,3))
print('A :\n'+str(A))
print('')
Ainv=inv(A)
print('Ainv = \n'+str(Ainv))
print('')
#Check
I=dot(A,Ainv)
print('I =\n'+str(I))
print('')
I=dot(A,Ainv)
print('I =\n'+str(I))
print('')
#Analytical result
Ana=array([52,17,2,-32,30,19,-9,-8,30])
print('Ana :\n'+str(Ana))
print('')
Ana=Ana/263
print('Ana =\n'+str(Ana))
print('')
Ana=Ana.reshape((3,3))
print('Ana =\n'+str(Ana))
print('')
#Difference between computed and analytical answer
Diff=Ainv-Ana
print('Difference =\n' +str(Diff))
print('')

A :[ 4 -2  1  3  6 -4  2  1  6]

A :
[[ 4 -2  1]
 [ 3  6 -4]
 [ 2  1  6]]

Ainv = 
[[ 0.19704433  0.06403941  0.00985222]
 [-0.12807882  0.10837438  0.09359606]
 [-0.04433498 -0.03940887  0.14778325]]

I =
[[1.00000000e+00 6.93889390e-18 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.77555756e-17 1.00000000e+00]]

I =
[[1.00000000e+00 6.93889390e-18 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.77555756e-17 1.00000000e+00]]

Ana :
[ 52  17   2 -32  30  19  -9  -8  30]

Ana =
[ 0.19771863  0.06463878  0.00760456 -0.121673    0.11406844  0.07224335
 -0.03422053 -0.03041825  0.11406844]

Ana =
[[ 0.19771863  0.06463878  0.00760456]
 [-0.121673    0.11406844  0.07224335]
 [-0.03422053 -0.03041825  0.11406844]]

Difference =
[[-0.0006743  -0.00059937  0.00224765]
 [-0.00640581 -0.00569406  0.02135271]
 [-0.01011444 -0.00899062  0.03371481]]



In [9]:
b=array([12,-25,32])
b=b.reshape((3,1))
x=solve(A,b)
print('x :\n'+str(x))
print('')
b=array([4,-10,22])
b=b.reshape((3,1))
x=solve(A,b)
print('x :\n'+str(x))
print('')
b=array([20,-30,+40])
b=b.reshape((3,1))
x=solve(A,b)
print('x :\n'+str(x))
print('')

x :
[[ 1.07881773]
 [-1.25123153]
 [ 5.18226601]]

x :
[[0.36453202]
 [0.46305419]
 [3.4679803 ]]

x :
[[ 2.4137931 ]
 [-2.06896552]
 [ 6.20689655]]



### An example involving complex numbers

In [10]:
a=2
b=4
A=array([a,b,-b,a])
A=A.reshape((2,2))
Es,evectors=eig(A)

print('Es = \n'+str(Es))
print('   ')

print('evectors matrix = \n'+str(evectors))
print('   ')



Es = 
[2.+4.j 2.-4.j]
   
evectors matrix = 
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        +0.70710678j 0.        -0.70710678j]]
   


In [13]:
A=array([-2,2,-3,2,1,-6,-1,-2,0])
A=A.reshape(3,3)
Es,evectors=eig(A)
print('Es = \n'+str(Es))
print('   ')
print('evectors matrix = \n'+str(evectors))
print('   ')
x=dot(Es[1],evectors[0:3,2])
print('x1 = \n'+str(x))
print('   ')
analytical=array([-1,-2,1]).reshape(3,1)/sqrt(6)
print('Analytical =\n '+str(analytical))
print('   ')
LHS=dot(A,analytical)
print('LHS = \n'+str(LHS))
print('   ')
RHS=dot(Es[1],analytical)
print('RHS = \n'+str(RHS))
print('   ')
print('LHS = RHS proves that the corresponding eigen vector being proportional to eigenvalue =5 ')
print('   ')
analytical=array([-2,1,0]).reshape(3,1)/sqrt(5)
LHS=dot(A,analytical)
print('LHS = \n'+str(LHS))
print('   ')
RHS=dot(Es[0],analytical)
print('RHS = \n'+str(RHS))
print('   ')
print('LHS = RHS proves that the corresponding eigen vector being proportional to eigenvalue = -3 ')
print('   ')
analytical=array([3,0,1]).reshape(3,1)/sqrt(10)
LHS=dot(A,analytical)
print('LHS = \n'+str(LHS))
print('   ')
RHS=dot(Es[2],analytical)
print('RHS = \n'+str(RHS))
print('   ')
print('LHS = RHS proves that the corresponding eigen vector being proportional to eigenvalue = -3 ')
print('   ')


Es = 
[-3.  5. -3.]
   
evectors matrix = 
[[-0.95257934  0.40824829  0.05155221]
 [ 0.27216553  0.81649658  0.82292764]
 [-0.13608276 -0.40824829  0.5658025 ]]
   
x1 = 
[0.25776107 4.1146382  2.82901249]
   
Analytical =
 [[-0.40824829]
 [-0.81649658]
 [ 0.40824829]]
   
LHS = 
[[-2.04124145]
 [-4.0824829 ]
 [ 2.04124145]]
   
RHS = 
[[-2.04124145]
 [-4.0824829 ]
 [ 2.04124145]]
   
LHS = RHS proves that the corresponding eigen vector being proportional to eigenvalue =5 
   
LHS = 
[[ 2.68328157]
 [-1.34164079]
 [ 0.        ]]
   
RHS = 
[[ 2.68328157]
 [-1.34164079]
 [ 0.        ]]
   
LHS = RHS proves that the corresponding eigen vector being proportional to eigenvalue = -3 
   
LHS = 
[[-2.84604989]
 [ 0.        ]
 [-0.9486833 ]]
   
RHS = 
[[-2.84604989]
 [ 0.        ]
 [-0.9486833 ]]
   
LHS = RHS proves that the corresponding eigen vector being proportional to eigenvalue = -3 
   


### Physical system with N couples equations and N unknowns (Hilbert Matrices)

In [14]:
A=array([])
for i in range(1,101):
    for j in range(1,101):
        a=1/(i+j-1)
        A=append(A,a)
A=A.reshape((100,100))
print('A =\n'+str(A))
print('  ')
B=A[0:100,0].reshape(100,1)
print('B = \n'+str(B))
print('  ')
y=solve(A,B)
print('y = \n'+str(y))

A =
[[1.         0.5        0.33333333 ... 0.01020408 0.01010101 0.01      ]
 [0.5        0.33333333 0.25       ... 0.01010101 0.01       0.00990099]
 [0.33333333 0.25       0.2        ... 0.01       0.00990099 0.00980392]
 ...
 [0.01020408 0.01010101 0.01       ... 0.00512821 0.00510204 0.00507614]
 [0.01010101 0.01       0.00990099 ... 0.00510204 0.00507614 0.00505051]
 [0.01       0.00990099 0.00980392 ... 0.00507614 0.00505051 0.00502513]]
  
B = 
[[1.        ]
 [0.5       ]
 [0.33333333]
 [0.25      ]
 [0.2       ]
 [0.16666667]
 [0.14285714]
 [0.125     ]
 [0.11111111]
 [0.1       ]
 [0.09090909]
 [0.08333333]
 [0.07692308]
 [0.07142857]
 [0.06666667]
 [0.0625    ]
 [0.05882353]
 [0.05555556]
 [0.05263158]
 [0.05      ]
 [0.04761905]
 [0.04545455]
 [0.04347826]
 [0.04166667]
 [0.04      ]
 [0.03846154]
 [0.03703704]
 [0.03571429]
 [0.03448276]
 [0.03333333]
 [0.03225806]
 [0.03125   ]
 [0.03030303]
 [0.02941176]
 [0.02857143]
 [0.02777778]
 [0.02702703]
 [0.02631579]
 [0.02564103

## Gamma matrices

In [33]:
Sigma1=array([0,1,1,0]).reshape(2,2)
Sigma2=array([0,complex(0-1j),complex(0+1j),0]).reshape(2,2)
Sigma3=array([1,0,0,-1]).reshape(2,2)
Zero= zeros(4).reshape(2,2)
Gamma2=block([[Zero,Sigma2],[-Sigma2,Zero]])
print('Gamma2 = \n'+str(Gamma2))
print('')
print('Gamma2 inverse = \n'+str(inv(Gamma2)))
print('')
print(' -Gamma2  = \n'+str(-1*(Gamma2)))
print('')
Gamma2_conjugate=conj(Gamma2)
Hermitian_conjugate=Gamma2_conjugate.T
print('Hermitian conjugate = \n'+str(Hermitian_conjugate))
print('')
print('Hence Gamma2 inverse = -Gamma2 = Hermitian conjugame of Gamma2')
print('')
Gamma1=block([[Zero,Sigma1],[-Sigma1,Zero]])
print('Gamma1 = \n'+str((Gamma1)))
print('')
Gamma3=block([[Zero,Sigma3],[-Sigma3,Zero]])
print('Gamma3 = \n'+str((Gamma3)))
print('')
LHS=dot(Gamma1,Gamma2)
print('Gamma1*Gamma2 = LHS \n'+str(LHS))
print('')
RHS=complex(0-1j)*block([[Sigma3,Zero],[Zero,Sigma3]])
print('RHS \n'+str(RHS))
print('')
print('LHS=RHS, Hence the realtion is satisfied aswell')

Gamma2 = 
[[ 0.+0.j  0.+0.j  0.+0.j  0.-1.j]
 [ 0.+0.j  0.+0.j  0.+1.j  0.+0.j]
 [-0.-0.j -0.+1.j  0.+0.j  0.+0.j]
 [-0.-1.j -0.-0.j  0.+0.j  0.+0.j]]

Gamma2 inverse = 
[[-0.+0.j -0.+0.j -0.+0.j -0.+1.j]
 [ 0.-0.j  0.-0.j  0.-1.j  0.-0.j]
 [ 0.+0.j  0.-1.j  0.+0.j  0.+0.j]
 [ 0.+1.j  0.+0.j  0.+0.j  0.+0.j]]

 -Gamma2  = 
[[-0.+0.j -0.+0.j -0.+0.j  0.+1.j]
 [-0.+0.j -0.+0.j -0.-1.j -0.+0.j]
 [ 0.+0.j  0.-1.j -0.+0.j -0.+0.j]
 [ 0.+1.j  0.+0.j -0.+0.j -0.+0.j]]

Hermitian conjugate = 
[[ 0.-0.j  0.-0.j -0.+0.j -0.+1.j]
 [ 0.-0.j  0.-0.j -0.-1.j -0.+0.j]
 [ 0.-0.j  0.-1.j  0.-0.j  0.-0.j]
 [ 0.+1.j  0.-0.j  0.-0.j  0.-0.j]]

Hence Gamma2 inverse = -Gamma2 = Hermitian conjugame of Gamma2

Gamma1 = 
[[ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0. -1.  0.  0.]
 [-1.  0.  0.  0.]]

Gamma3 = 
[[ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]
 [-1.  0.  0.  0.]
 [ 0.  1.  0.  0.]]

Gamma1*Gamma2 = LHS 
[[0.-1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j]
 [0.+0.j 0.+0.

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [15]:
#from vpython import *
from numpy.linalg import solve
#scene = canvas(x=0,y=0,width=1600, height =800,title='String and masses configuration')
#tempe = curve(x=range(0,500) , color=color.black )
n=9
eps = 10**(-3)
deriv = zeros((n,n) , float )
f = zeros( (n) , float )
x = array ([0.5,0.5,0.5,0.5, 0.5 , 0.5 , 0.5 , 1.0 , 1.0 , 1.0])
#def plotconfig() :
    
    #for obj in scene . objects :
        
        #obj.visible =0 # Erase previous configuration
    #L1 = 3.0
    #L2 = 4.0
    #L3 = 4.0
    #{xa = L1*x[3] # L1* cos ( th1 )
    #ya = L1*x[0] # L1 s in ( th1 )
    #xb = xa+L2*x[4] # L1* cos ( th1 )+L2* cos ( th2 )
    #yb = ya+L2*x[1] # L1* s in ( th1 )+L2* sen ( th2 )
    #xc = xb+L3*x[5] # L1* cos ( th1 )+L2* cos ( th2 )+L3* cos ( th3 )
    #yc = yb−L3*x[2] # L1* s in ( th1 )+L2* sen ( th2 )−L3* sin ( th3 )
    #mx = 100.0 # for linear coordinate transformation
    #bx = -500.0 # from 0=< x =<10
    #my = -100.0 # to −500 =<x_window=>500
    #by = 400.0 # same transformat ion for y
    #xap = mx*xa+bx # to keep aspect ra t io
    #yap = my*ya+by
    #ball1 = sphere(pos=vec(xap,yap,0),color=color.cyan,radius=15)
    #xbp = mx*xb+bx
    #ybp = my* yb+by
    #ball2 = sphere(pos=vec(xbp , ybp,0 ) , color=color.cyan,radius =25)
    #xcp = mx*xc+bx
    #ycp = my*yc+by
    #x0 = mx*0+bx
    #y0 = my*0+by
    #line1 = curve( pos =[( x0 , y0 ) , ( xap , yap ) ] , color=color.yellow,radius =4)
    #line2 = curve ( pos =[( xap , yap ) , ( xbp , ybp ) ] , colo r=colo r.yellow , radius =4)
    #line3 = curve ( pos =[( xbp , ybp ) , ( xcp , ycp ) ] , colo r=colo r.yellow , radius =4)
    #topline = curve ( pos =[( x0 , y0 ) , ( xcp , ycp ) ] , color=color.red , radius =4)
def F(x,f) :# F function
    f[0] = 3*x[3] + 4*x[4] + 4*x[5]- 8.0
    f[1] = 3*x[0] + 4*x[1] - 4*x[2]
    f[2] = x[6]*x[0] - x[7]*x[1] -10.0
    f[3] = x[6]*x[3] - x[7]*x[4]
    f[4] = x[7]*x[1] + x[8]*x[2] - 20.0
    f[5] = x[7]*x[4] - x[8]*x[5]
    f[6] = pow(x[0] , 2) + pow(x[3] , 2) - 1.0
    f[7] = pow(x[1],2) + pow(x[4] , 2) - 1.0
    f[8] = pow(x[2] , 2) + pow(x[5] , 2) - 1.0
def dFi_dXj(x , deriv , n) : # Derivatives
    h = 10**(-4)
    
    for j in range(0,n) :
        temp = x[j]
        x[j] = x[j] + h/2.
        F(x,f)
    
        for i in range(0,n): 
            deriv[i,j] = f[i]
            
        x[j] = temp
    for j in range(0,n) :
        temp = x[j]
        x[j] = x[j ] - h/2.
        F(x, f )
        for i in range(0 , n) : 
            deriv[i ,j] = ( deriv[i,j] - f[i]) /h
        x[ j ] = temp

for it in range(1 , 100) :
    #rate(1) # 1 second between graphs
    F(x, f )
    dFi_dXj(x , deriv , n)
    B = array([[-f[0]] , [-f[1]] , [-f[2]] , [-f[3]] , [-f[4]] , [-f[5]],[-f[6]] , [-f[7]] , [- f[8]]])
    sol = solve( deriv , B)
    dx = sol[:,0] # F i r s t column o f so l

    for i in range(0 , n) :
        x[ i ] = x[ i ] + dx[ i ]
    #plotconfig ()
    errX = errF = errXi = 0.0
    for i in range(0 , n) :
        if(x[i] != 0.0) : 
            errXi = abs( dx[i]/x[i] )
        else : errXi = abs( dx[ i ] )
        if ( errXi > errX ) : 
            errX = errXi
        if ( abs( f[ i ]) > errF ) : 
            errF = abs( f[i ])
        if( ( errX <= eps ) and ( errF<= eps ) ) : 
            break
print( 'Number of iterations = ', it , '\n Final Solution :')
for i in range(0,n) :
    print ( 'x['+str(i)+'] =' +str(x[i]))


Number of iterations =  99 
 Final Solution :
x[0] =0.7610026921018717
x[1] =0.26495381028070264
x[2] =0.8357058293571064
x[3] =0.6487487207029421
x[4] =0.9642611048972873
x[5] =0.549177354575506
x[6] =17.16020978460729
x[7] =11.545279684327756
x[8] =20.271578044639117
